/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package codeberg.org/nickoan/ntee-r1quest/ntee-db/capi */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 14 "exports.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* nteedb_open(char* dir, char* optsJSON);

// nteedb_close and nteedb_drop are deliberately idempotent: an unknown or
// already-released handle succeeds silently (unlike data ops, which return
// errInvalidHandle) so teardown paths can never fail on a double close.
//
extern char* nteedb_close(unsigned int h);
extern char* nteedb_drop(unsigned int h);
extern char* nteedb_destroy(char* dir);
extern char* nteedb_put(unsigned int h, char* key, unsigned char* val, int valLen, char* ixJSON);
extern char* nteedb_get_json(unsigned int h, char* key);
extern char* nteedb_get_many_json(unsigned int h, char* keysJSON);
extern char* nteedb_has(unsigned int h, char* key);
extern char* nteedb_stats(unsigned int h);
extern char* nteedb_delete(unsigned int h, char* key);
extern char* nteedb_put_batch(unsigned int h, char* itemsJSON);
extern char* nteedb_put_batch_bin(unsigned int h, char* metaJSON, unsigned char* blob, int blobLen);
extern char* nteedb_prefix_scan(unsigned int h, char* prefix);
extern char* nteedb_by_index(unsigned int h, char* name, char* valJSON, int limit);
extern char* nteedb_by_index_records_json(unsigned int h, char* name, char* valJSONStr, int limit);
extern char* nteedb_by_index_prefix_records_json(unsigned int h, char* name, char* prefix, int limit);
extern char* nteedb_prefix_scan_records_json(unsigned int h, char* prefix);
extern char* nteedb_by_index_has(unsigned int h, char* name, char* valJSON);
extern char* nteedb_by_index_prefix(unsigned int h, char* name, char* prefix, int limit);
extern char* nteedb_by_index_range(unsigned int h, char* name, char* loJSON, char* hiJSON);
extern char* nteedb_remove_by_pk_less(unsigned int h, char* cutoff);
extern char* nteedb_remove_by_pk_greater(unsigned int h, char* cutoff);
extern char* nteedb_compact(unsigned int h);
extern char* nteedb_reindex(unsigned int h);
extern char* nteedb_dropped_indexes(unsigned int h);
extern char* nteedb_prospective_indexes(unsigned int h);
extern void nteedb_free(void* p);

#ifdef __cplusplus
}
#endif
